### ISSUE TITLE
Basic Installation Instructions 

### ISSUE THREAD

**Issue by smitp33** [keis/panel-plugin-gauge#1]
Really interested in looking at this. As a newbie to Grafana it does not appear to obvious how to install it.

Have tried simply placing under /usr/share/grafana/public/app/plugins/gauge but does not then appear to be available within the GUI. 

Would it be possible to provide some short instructions?

**Comment by keis** [comment]
Hi.

First off, I'm not entirely sure about the future of this repo depending on what happens with grafana/grafana#3688. Also this repo is behind the code on that PR and really needs an update.

regardless, I think the location you want is `$grafana/data/plugins/`

**Comment by smitp33** [comment]
@keis Thanks for pointing me at the other PR - missed that one completely when I was looking at what other things were available for Grafana. Hope they do pull it in as I think it's a really neat idea.
